<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Adding the thruster units with the macro created in snippets.xacro -->
    <!--
    Important:
        - The thruster IDs must be given as integers and must be unique to each thruster unit
        - The thruster pose in the <origin> block is relative to the body's center of mass. Be
          aware that Gazebo does not use the SNAME convention per default.
    -->

    <xacro:thruster_macro robot_namespace="${namespace}" thruster_id="0">
        <origin xyz="${-riptide_length*0.505} 0 0" rpy="0 0 ${0}" />
    </xacro:thruster_macro>

    <!-- Instantiate fins, if necessary -->
    <xacro:fin_macro namespace="${namespace}" fin_id="0" mesh_filename="${fin_mesh_file}">
      <origin xyz="${-riptide_length*0.20} 0 ${riptide_radius}" rpy="0 0 0" />
    </xacro:fin_macro>

    <xacro:fin_macro namespace="${namespace}" fin_id="1" mesh_filename="${fin_mesh_file}">
      <origin xyz="${-riptide_length*0.20} ${riptide_radius*0.866} ${-riptide_radius*0.5}" rpy="${-2*pi/3} 0 0"/>
    </xacro:fin_macro>

    <xacro:fin_macro namespace="${namespace}" fin_id="2" mesh_filename="${fin_mesh_file}">
      <origin xyz="${-riptide_length*0.20} ${-riptide_radius*0.866} ${-riptide_radius*0.5}" rpy="${2*pi/3} 0 0"/>
    </xacro:fin_macro>

</robot>
